substitutions:
  _GOOGLE_CLIENT_ID: "690018681390-b871npco41agqt652a2vp8a2jg7u01kp.apps.googleusercontent.com"
  _GOOGLE_REDIRECT_URI: "https://kelas-pbo.fun/auth/recall"
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gim-ppbo:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gim-ppbo:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gim-ppbo'
      - '--image=gcr.io/$PROJECT_ID/gim-ppbo:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'

      # 🔑 Cloud SQL Connector
      - '--add-cloudsql-instances=$PROJECT_ID:asia-southeast1:mysql-8-2v-10g-singapore'

      # 🌱 Environment (NON-sensitive)
      - '--set-env-vars=DB_NAME=kelas_pbo,DB_USER=app_user,GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_REDIRECT_URI=${_GOOGLE_REDIRECT_URI}'

      # 🔐 Secret Manager (perlu setup ke G-Cloud Security / Secret Manager)
      - '--set-secrets=DB_PASSWORD=db-password:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest'

images:
  - 'gcr.io/$PROJECT_ID/gim-ppbo:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY